### ISSUE TITLE
Handle UCAN delegation

### ISSUE THREAD

**Issue by blaine** [fission-codes/fission-server#115]
# Summary

## Problem

Currently the server only accepts UCANs whose `iss` field matches the `did` of the account in question. The database lookup happens by `did` and `username` (allowing a single did to control multiple accounts). However, the controlling `did` may have delegated access to an agent. In that case, the `iss` field of the UCAN won't match the account. Instead, one of the `prf` UCANs will contain the relevant `did`. We need to handle that case.

## Solution

Likely as follows:

1. Remove `did` from database query, since we don't know the `did` in advance.
2. Figure out how the `rs-ucan` proof chain works. What I'd really like is something like `async fn ucan.has_capability(from_did: Did, capability: Capability) -> Result<bool, Err>`, that will recursively check the UCAN and and any UCANs in `prf`, but I'm not sure it does that in a straightforward way (?).
3. Add this to the routes. It might make sense to fetch the account in all cases; possibly slower, but it's looking like we'll do that anyhow in all the relevant routes, but maybe not?

**Comment by blaine** [comment]
@icidasset does this seem accurate? It won't be a big refactor, but I realized this morning that our server doesn't allow for delegated UCANs at all (my fault!). 🤦‍♀️ Just adding this to track it / for discussion as necessary. We'll also want to figure out what the delegation capabilities are per this morning's conversation, but I'm not too worried about that as they'll basically just be constants and trivially changed.

**Comment by icidasset** [comment]
Yeah, this is one of the things I wanted to do in my "UCAN work part 2". Which I most likely won't get to soon because there's so much SDK work to be done. Also I was waiting on the rs-ucan update, pretty sure the delegation chain stuff is changing quite a bit in their v0.10 update.

Anyhow, problem description seems largely accurate 👍 The authority extractor needs to go through the UCAN proofs and find the root issuer. If it is missing any UCANs the server needs to report this back to the client following this spec: https://github.com/ucan-wg/ucan-as-bearer-token#333-missing-proofs UCANs are stored in a database or some other caching system.

> Remove did from database query, since we don't know the did in advance.

Not sure what you mean by this.
Other solution notes make sense.
