### ISSUE TITLE
sql: DID Reference table

### ISSUE THREAD

**Issue by pinkforest** [fission-codes/fission-server#38]
Foreign key users.id (UUIDv4 generated upon CREATE)

Users can have multiple DID's with various attributes e.g. attested / verified etc.

**Comment by expede** [comment]
> Users can have multiple DID's with various attributes e.g. attested / verified etc.

Users have a single DID for the forseeablw future, and all delegation is handled via UCAN

**Comment by blaine** [comment]
@expede I'm a little confused, because I think the reversion to the single-did:key-model undermines a lot of the things I was hoping to achieve with what we were talking about yesterday.

I'll use a user story to illustrate: I have two computers, and I want to be able to use both of them to interact with my Fission account. With the did:odd approach (or even a 1:N relationship for Fission User:did:key), I feel very comfortable that we can build a usable system to provision the keys.

If it's 1:1 user:key and I need to provision access, I _techincally_ can delegate the key, but in practice, what does that look like? I can imagine a bunch of methods, but none that are easy from the user's perspective, even assuming a technically adept user. Maybe I'm missing something obvious?

**Comment by blaine** [comment]
Ok! Chatted with @expede and I didn't have AWAKE/MLS in my head to do delegation. Sticking with a 1:1 user:did makes sense here, because in the scenario where we store a did:odd as the root key, AWAKE/MLS-mediated delegation will still work, but if someone wants to use a did:key instead, they can do that (with the caveat that we won't be able to recover for them in the event that they lose the key modulo a recovery kit).

I was confused because @expede and I had discussed keeping a record of the various (did:key-issued) UCANs that users had on their various devices (ssh-key style) in order to facilitate revocation (as you can do in the github UI), which *is* a 1:M relationship, BUT that's for a totally different use-case. We wouldn't be using the records in that table as an authorization root, and in addition we'd refer to the UCAN hashes and not the public keys.

**Comment by pinkforest** [comment]
Ok since we are not doing did reference mapping in database I'll close this one since it doesn't concern server afaik.
